services:
- type: web
  name: ghost
  env: docker
  autoDeploy: false
  disk:
    name: ghost
    mountPath: /var/lib/ghost/content
    sizeGB: 10
  envVars:
    - key: database__client
      value: pg
    - key: database__connection__host
      fromService:
        type: pserv
        name: postgres
        property: host
    - key: database__connection__database
      value: ghostdb
    - key: database__connection__user
      value: postgres
    - key: database__connection__password
      fromService:
        type: pserv
        name: postgres
        envVarKey: POSTGRES_PASSWORD

- type: pserv
  name: postgres
  plan: free
  env: docker
  repo: https://github.com/render-examples/postgres
  autoDeploy: false
  disk:
    name: postgres
    mountPath: /var/lib/postgresql/data
    sizeGB: 1
  envVars:
    - key: POSTGRES_DB
      value: ghostdb
    - key: POSTGRES_USER
      value: postgres
    - key: POSTGRES_PASSWORD
      generateValue: true
