services:
- type: web
  name: ghost
  env: docker
  autoDeploy: false
  disk:
    name: ghost
    mountPath: /var/lib/ghost/content
    sizeGB: 10 # Feel free to change this to suit your needs.
  envVars:
    - key: database__client
      value: pg
    - key: database__connection__host
      fromService:
        type: pserv
        name: postgresql
        property: host
    - key: database__connection__database
      fromService:
        type: pserv
        name: postgresql
        property: database
    - key: database__connection__user
      fromService:
        type: pserv
        name: postgresql
        property: user
    - key: database__connection__password
      fromService:
        type: pserv
        name: postgresql
        property: password

- type: pserv
  name: postgresql
  plan: free
  env: docker
  repo: https://github.com/render-examples/postgres
  autoDeploy: false
  disk:
    name: postgresql
    mountPath: /var/lib/postgresql/data
    sizeGB: 1
  envVars:
    - key: POSTGRES_DB
      value: ghostdb
    - key: POSTGRES_USER
      value: ghostuser
    - key: POSTGRES_PASSWORD
      generateValue: true
